name: Run parser now

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Parse and send via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 46.8.254.134
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/semenabot
            python3 parse.py
            python3 send.py
